### ISSUE TITLE
Error when updating list of images.

### ISSUE THREAD

**Issue by DenisMrGnusa** [JayTWWM/Image-Slider-Flutter#1]
I have an error when updating image list after widget get build. the error like below:

![image](https://user-images.githubusercontent.com/34623582/92078189-0f1d5e80-ede8-11ea-864d-78a72982ab5e.png)

How can I handle the error,

thank you,
best regards

**Comment by yasinakcadev** [comment]
I got the same error. Is there a way that I can customize tabController's length property dynamically?

**Comment by JayTWWM** [comment]
Yes, you have to make your own tabController and put that in the slider. Also, can you give you give me your code so that I know what's wrong?
Please check if the number of children you have given is equal to what length you put in tabController at every point of time.
`TabController(length: your_length, vsync: whatever)`
